name: Checks

on: [push]

jobs:
  build:
    name: Run the Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout into repository
    - uses: actions/checkout@v2
    - run: npm install && npm run test:ci 
